GET http://localhost:3001/users


###

GET http://localhost:3001/users/16


###

POST http://localhost:3001/users 
Content-Type: application/json

{
    "username": "admin2",
    "email": "admin2@mail.com",
    "password": "admin2",
    "phone": "089988776655",
    "storename": "KasirApp"
}


###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "admin2"
}


###



GET http://localhost:3001/category


###

GET http://localhost:3001/category/1


###

POST http://localhost:3001/category
Content-Type: application/json

{
    "name": "buah"
}

###

PATCH http://localhost:3001/category/4
Content-Type: application/json

{
    "name": "iceCreamm"
}

###

DELETE http://localhost:3001/category/5

###

GET http://localhost:3001/product

###

POST http://localhost:3001/product
Content-Type: application/json

{
    "name": "Nasi Goreng",
    "email": "admin2@mail.com",
    "password": "admin2",
    "phone": "089988776655",
    "storename": "KasirApp"
}
